sudo: required
language: node_js

notifications:
  email: true

matrix:
  fast_finish: true
  include:
    ########
    # OS X #
    ########

    - name: '[OSX] macOS 10.13 // Xcode 9.3 // Node.js v6.x'
      os: osx
      osx_image: xcode9.3
      node_js: '6'

    - name: '[OSX] macOS 10.13 // Xcode 9.3 // Node.js v8.x'
      os: osx
      osx_image: xcode9.3
      node_js: '8'

    - name: '[OSX] macOS 10.13 // Xcode 9.3 // Node.js v10.x'
      os: osx
      osx_image: xcode9.3
      node_js: '10'

    - name: '[OSX] macOS 10.13 // Xcode 10 // Node.js v10.x'
      os: osx
      osx_image: xcode10
      node_js: '10'

    - name: '[OSX] macOS 10.14 // Xcode 10.2.1 // Node.js v10.x'
      os: osx
      osx_image: xcode10.2
      node_js: '10'
      after_success:
        - 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
        - semantic-release

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run lint
  - npm run report-coverage
  - npm run build
